[WIP] Added management command for initial Open Zaak setup
maykinmedia/open-zaak pull request #1
Opened 2020-05-25 15:36 UTC by stevenbal

2020-05-29 09:22 UTC, stevenbal commented on src/openzaak/management/commands/setup_configuration.py
> +                client_ids=[f"open-zaak-{municipality}"],
@joeribekker this is step #4 under `Open Zaak` [here](https://open-zaak.readthedocs.io/en/latest/installation/configuration.html). In the manual it specifies that I can use any secret and that it doesn't need to be used in any other step, but for this application (that gives OZ access to notificaties) to work, the clientid/secret must also be registered in Open notificaties right?

Here I used the same clientid/secret as used by the external API credential that for Open Zaak -> Open Notificaties (step #2 in the manual), not sure if that's right

2020-05-29 13:07 UTC, joeribekker requested changes

2020-05-29 13:07 UTC, joeribekker commented on src/openzaak/management/commands/setup_configuration.py
> +            help="Specifies the domain for this Open Zaak installation",
Please provide examples in all help texts, and indicate what its used for.

2020-05-29 13:07 UTC, joeribekker commented on src/openzaak/management/commands/setup_configuration.py
> +            site.name = f"Open Zaak {municipality.capitalize()}"
Don't make it capitilized.

2020-05-29 13:07 UTC, joeribekker commented on src/openzaak/management/commands/setup_configuration.py
> +            site = Site.objects.get_current()
Please add references to the config docs to all sections.

```suggestion
            # See: https://open-zaak.readthedocs.io/en/latest/installation/configuration.html#setting-the-domain
            site = Site.objects.get_current()
```

2020-05-29 13:07 UTC, joeribekker commented on src/openzaak/management/commands/setup_configuration.py
> +                    label=f"Open Notificaties {municipality.capitalize()}",
remove cap

2020-05-29 13:07 UTC, joeribekker commented on src/openzaak/management/commands/setup_configuration.py
> +                    user_representation=f"Open Zaak {municipality.capitalize()}",
remove cap

2020-05-29 13:07 UTC, joeribekker commented on src/openzaak/management/commands/setup_configuration.py
> +                    user_id=f"open-zaak-{municipality}",
lower

2020-05-29 13:07 UTC, joeribekker commented on src/openzaak/management/commands/setup_configuration.py
> +                    client_id=f"open-zaak-{municipality}",
lower

2020-05-30 10:53 UTC, joeribekker approved these changes

2020-05-30 10:54 UTC, merged